### ISSUE TITLE
I look forward to leveraging my extensive experience and knowledge to contribute to your team’s goals and achievements.

### ISSUE THREAD

**Issue by kentaurse** [BizNetBB/frontend#8]
Hi, I'm Ethan Tan, an expert in web full-stack and blockchain development with over 8 years of experience. I specialize in crafting durable, scalable web applications and innovative blockchain solutions. My proficiency in React.js, Vue.js, and Next.js, along with my expertise in Solidity for smart contracts, ensures I deliver superior, secure, and efficient solutions designed to meet your unique objectives.

**Comment by Jaro-c** [comment]
Hi @kentaurse,

Thank you for your interest and for taking the time to open an issue in our repository. However, at this time, we are not seeking external collaboration on our projects.

Best regards,
@Jaro-c

**Comment by kentaurse** [comment]
If you need developer, plz contact me
